spring.application.name=TeamTaskManager
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d7qk2enavr4c73ev7dhg-a.oregon-postgres.render.com:5432/teamtaskmanager_r75f?sslmode=require
spring.datasource.username=teamadmin
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=ThisIsMySecureSecretKeyForJWT123456789
jwt.expiration=86400000